"""Initial migration

Revision ID: ca11fd60d728
Revises: 
Create Date: 2026-01-04 13:40:11.519053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca11fd60d728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_line', schema=None) as batch_op:
        batch_op.alter_column('tahun',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(2026)'))

    with op.batch_alter_table('job_detail', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'User'"))
        batch_op.alter_column('pic',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_detail', schema=None) as batch_op:
        batch_op.alter_column('pic',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'User'"))

    with op.batch_alter_table('budget_line', schema=None) as batch_op:
        batch_op.alter_column('tahun',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(2026)'))

    # ### end Alembic commands ###
